import collections from "./collections.js";
import instances from "./instances.js";
import list_items from "./list_items.js";
import list_items_lookup from "./list_items_lookup.js";
import public_records from "./public_records.js";
import records from "./records/records.service.js";
import relationships from "./relationships.js";
import review_changes from "./review_changes.js";
import settings from "./settings.js";
import snapshots from "./snapshots.js";
import unified_collections from "./unified_collections.js";
import unified_records from "./unified_records.js";
import unified_search from "./unified_search/unified_search.service.js";
import users from "./users/users.service.js";

export default (function (app) {
  app.configure(users);
  app.configure(records);
  app.configure(relationships);
  app.configure(list_items);
  app.configure(instances);
  app.configure(collections);
  app.configure(unified_records);
  app.configure(unified_collections);
  app.configure(list_items_lookup);
  app.configure(review_changes);
  app.configure(public_records);
  app.configure(snapshots);
  app.configure(settings);
  app.configure(unified_search);
});
